### ISSUE TITLE
Electrical Age server

### ISSUE THREAD

**Issue by Domi1993** [AMIDIBOSS/Visual-Basic#1]
Hello i saw that you wrote here:

https://github.com/Electrical-Age/ElectricalAge/issues/508

That you have a server thats running the electricalage mod, i searched long time for a server with this mod. 

Can you give me the IP of this server

**Comment by AMIDIBOSS** [comment]
No, I'm sorry. It's private server, for frends only.
I hope you'll understand

**Comment by Domi1993** [comment]
Ok
